<aside>
    <div class="panel-primary panel">
        <div class="panel-heading"><h4 class="panel-title">USUARIOS</h4></div>
    </div>
    <div class="panel panel-body">
    <form class="form-inline form-group" id="filter_1">                    
        <label>Filtrar por: </label>
        <div class="btn-group">
            <button class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="sel" type="button"><h7>Seleccione...</h7><span class="caret"></span></button>
            <ul class="dropdown-menu sel" role="menu">
                <li><a href='#'>Usuario</a></li>
                <li><a href='#'>Perfil</a></li>
                <li><a href='#'>Estado</a></li>
                <li><a href='#'>Cedula</a></li>
            </ul>
        </div>
        <div class="form-group">
        <input type="text" name="usuario" class="form-control" >
        </div>
        
    </form>
        <div style="text-align: right" class="form-group">
        <button type="button" class="btn btn-danger" name="other" id="other">Añadir otro filtro</button>
        <input type="button" value="Buscar" class="btn btn-danger"/>
        </div>
    </div>
    
    <div style="box-shadow: 1px 0px 5px 1px #cccccc;" class="panel panel-body">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center">Cuenta</th>
                    <th class="text-center">Usuario</th>
                    <th class="text-center">Cargo</th>
                    <th class="text-center">Perfil</th>
                    <th class="text-center">Estado</th>
                    <th class="text-center">Identificación</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->datos as $d) : ?>
                <tr>
                    <td><?php echo $d->nombre_usuario; ?></td>
                    <td><?php echo $d->nombre_real . " " . $d->apellido_real; ?></td>
                    <td><?php echo $this->escape($d->cargo); ?></td>
                    <td><?php echo $this->escape($d->perfil); ?></td>
                    <td><?php echo $this->escape($d->estado); ?></td>
                    <td><?php echo $this->escape($d->identificacion); ?></td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle"data-toggle="dropdown">
                              Opciones <span class="caret"></span>
                            </button>

                            <ul class="dropdown-menu" role="menu">
                              <li>
                                  <a href="<?php echo $this->url(array('module' => 'Usuarios', 'controller' => 'Usuario', 'action' => 'actualizarusuario', 'id' => $d->nombre_usuario)); ?>">
                                      Editar
                                  </a>
                              </li>
                              <li class="divider"></li>
                              <li><a href="#">Eliminar</a></li>
                            </ul>
                          </div>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div align="right" style="margin-top: 20px;">
        <a class="btn btn-danger" data-toggle="modal" data-target="#loginModal">Ingresar nuevo usuario</a>
        </div>
        <!--Modal que contiene el formulario de añadir-->
        <?php echo $this->action('crearusuario', 'Usuario', 'Usuarios'); ?>
        <!---------------------------------------------->
        
       

<script>
    $(document).ready(function(){
        var i=0;
        $('.dropdown-toggle').dropdown();
         $(function(){
            $(".sel").on('click', 'li a', function(){
                $("[id=sel] > h7").text($(this).text());
                $("[id=sel]").val($(this).text());
            });
        });
        $('#other').click(function(){
            $('#filter_1').clone().appendTo('#filter_1').attr('id','filter_'+i);
            i++;
        });
    });
</script>
    </div>
    
</aside>
