<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Nuevo estado de crédito</h4>
            </div>
            <div class="modal-body">
                <!-- The form is placed inside the body of modal -->
                <form id="insertEstado" method="post" class="form-horizontal"><!--id="loginForm"--> 
                    <div class="form-group">
                        <?php echo $this->crear->getElement('id_estado_credito'); ?>
                        <label class="col-xs-4 control-label">Nombre estado de crédito</label>
                        <div class="col-xs-7">
                            <?php echo $this->crear->getElement('nombre_estado_credito'); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-4 control-label">Descripción</label>
                        <div class="col-xs-7">
                            <?php echo $this->crear->getElement('descripcion_estado_credito'); ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-5 col-xs-offset-3">
                            <?php echo $this->crear->getElement('insertar'); ?>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>