<aside>
    <div class="panel-primary panel">
        <div class="panel-heading"><h4 class="panel-title">ACTUALIZAR TIPO DE MODALIDAD DE CRÉDITO</h4></div>
    </div>
    <form class="panel panel-body" style="box-shadow: 1px 0px 5px 1px #cccccc;" method="post">
        <table >
            <tr>
                <?php echo $this->form->getElement('cod_tipo_modalidad_credito'); ?>
                <td>Nombre tipo de modalidad</td>
                <td><?php echo $this->form->getElement('nombre_tipo_modalidad'); ?></td>
                <td>Descripción tipo de modalidad</td>
                <td><?php echo $this->form->getElement('descripcion_tipo_modalidad'); ?></td>
            </tr>
            <tr><td>&nbsp;</td></tr>
            <tr>
                <td colspan="4" align="right"><?php echo $this->form->getElement('submit'); ?></td>
                <td><button class="btn btn-default" onclick="location.href='<?php echo $this->url(array('module'=>'TipoModalidad','controller'=>'TipoModalidad','action'=>'index')); ?>'">Cancelar</button></td>
            </tr>
        </table>
    </form>
<?php //echo $this->form; ?>
</aside>