<div id="verModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><strong>Tipo Modalidad de crédito</strong></h4>
            </div>
            <div class="modal-body">
                <div class="well">
                    <h5><strong><div id="muestranom" align="left"></div></strong></h5>
                    <p id='texto' align="justify" ></p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
                <!--<button type="button" class="btn btn-primary">Save changes</button>-->
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Confirma Eliminar</h4>
            </div>

            <div class="modal-body">
                <p>Esta a punto de eliminar el registro, este procedimiento es irreversible.</p>
                <p>¿Desea confirmar la operación?</p>
                <!--<p class="debug-url"></p>-->
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <a href="#" class="btn btn-danger danger">Eliminar</a>
            </div>
        </div>
    </div>
</div>
<aside>
    <div class="panel-primary panel">
        <div class="panel-heading"><h4 class="panel-title">TIPO DE MODALIDAD DE CRÉDITO</h4></div>
    </div>
    <div class="panel panel-body">
        <form class="form-inline form-group">                    
            <label>Filtrar por: </label>
            <div class="btn-group">
                <span class="label label-primary" style="padding: 5px;">Tipo Modalidad de crédito</span>
            </div>
            <div class="form-group">
                <select name="tipomodalidad" class="form-control">
                    <option value="">Seleccione...</option>
                    <?php foreach ($this->listar as $d) : ?>
                        <option value="<?php echo $d->cod_tipo_modalidad_credito; ?>">
                            <?php echo $d->nombre_tipo_modalidad; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div style="text-align: right" class="form-group">
                <input type="button" value="Buscar" class="btn btn-danger"/>
            </div>
        </form>
    </div>

    <div style="box-shadow: 1px 0px 5px 1px #cccccc;" class="panel panel-body">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center">Tipo Modalidad de crédito</th>
                    <th class="text-center">Descripción</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->listar as $d) : ?>
                    <tr>
                        <?php $idTipo = $d->cod_tipo_modalidad_credito; ?>
                        <td id="tdd<?php echo $idTipo; ?>" value="<?php echo $this->escape($d->nombre_tipo_modalidad); ?>"><?php echo $this->escape($d->nombre_tipo_modalidad); ?></td>
                        <td id='td<?php echo $idTipo; ?>' value="<?php echo $this->escape($d->descripcion_tipo_modalidad); ?>"><?php echo substr($this->escape($d->descripcion_tipo_modalidad), 0, 30) . "..."; ?></td>
                        <td>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle"data-toggle="dropdown">
                                    Opciones <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a data-toggle="modal" name='<?php echo $idTipo; ?>' href="#verModal">Ver</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->url(array('module' => 'TipoModalidad', 'controller' => 'TipoModalidad', 'action' => 'editartipomodalidad', 'id' => $idTipo)); ?>">Editar</a></li>
                                    <li class="divider"></li>
                                    <li>
                                        <a data-href="<?php echo $this->url(array('module' => 'TipoModalidad', 'controller' => 'TipoModalidad', 'action' => 'eliminartipomodalidad', 'id' => $idTipo)); ?>" data-toggle="modal" data-target="#confirm-delete" href="#">
                                            Eliminar
                                        </a>
                                    </li>
                                </ul>

                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
           
        </table>
        <p class="text-right" style="margin-top: 20px;">
            <button class="btn btn-danger" data-toggle="modal" data-target="#loginModal">Ingresar tipo modalidad de crédito</button>
        </p>
         <!--Modal que contiene el formulario de añadir-->
        <?php echo $this->action('creartipomodalidad', 'TipoModalidad', 'TipoModalidad'); ?>
        <!---------------------------------------------->
    </div>
</aside>
<script>
    $(document).ready(function() {
        $('.dropdown-toggle').dropdown();
        /*$('td:nth-child(2)').each(function(){
         if ($(this).text().length > 20)
         $(this).text($(this).text().substring(0,20));
         });*/
        $('a').click(function() {
            $('p[id=texto]').text($('td[id=td' + $(this).attr('name') + ']').attr('value'));
            $('div[id=muestranom]').text($('td[id=tdd' + $(this).attr('name') + ']').attr('value'));
        });
    });
    $('#confirm-delete').on('show.bs.modal', function(e)
    {
        $(this).find('.danger').attr('href', $(e.relatedTarget).data('href'));
        //$('.debug-url').html('Elimina registro: <strong>' + $(this).find('.danger').attr('href') + '</strong>');
    });
</script>