<?php echo $this->doctype() ?>
<html>
    <head>
	<?php $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset='.$this->getEncoding())->appendHttpEquiv('Content-Language', 'es-ES');
	echo $this->headMeta();
	$session = new Zend_Session_Namespace('SuperAdmin');
        $auth = Zend_Auth::getInstance()->getIdentity();
        $perfil=$auth->perfil;
	//$perfil = $authStorage->perfil;
	/*if (!isset($perfil))
	{
	  $session = new Zend_Session_Namespace('Admin1');
	  $perfil = $session->getNamespace();
	}*/
        $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
        $this->headLink()->appendStylesheet($baseUrl.'/bootstrap-3/dist/css/bootstrap.css');
	$this->headLink()->appendStylesheet($baseUrl.'/bootstrap-3/dist/js/bootstrap.min.js');
	$this->headLink()->appendStylesheet($baseUrl.'/css/css.css');
	$this->headLink()->appendStylesheet($baseUrl.'/bootstrap-3/examples/signin/signin.css');
        //$this->headLink()->appendStylesheet($baseUrl.'/bootstrap-3/js/modal.js');
	$this->headScript()->appendFile($baseUrl.'/bootstrap-3/assets/js/jquery.js');
	$this->headScript()->appendFile($baseUrl.'/bootstrap-3/dist/js/bootstrap.js');
	echo $this->headLink();
	echo $this->headTitle('ICETEX');
   echo $this->headScript();
	$this->headScript()->appendFile('/js/common.js');
	echo $this->headScript();?>
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo $baseUrl; ?>/imagenes/favicon.ico" />
    </head>
<body>
    <header>
	<img src="<?php echo $baseUrl;?>/imagenes/banner1.png" style="width: 100%;" />
    </header>
    <nav <?php if (isset($perfil)) { ?> class="navbar navbar-default" <?php } ?> >
      <?php if (isset($perfil)) {
	  echo $this->render('nav.phtml');
      } ?>
    </nav>
    <article style="margin-left: 5%;">
      <?php if (isset($perfil)){ ?>
      <div role="navigation" class="list-group">
	<?php echo $this->render('menu.phtml'); ?>
      </div>
      <?php }?>
    </article>
    <?php echo $this->layout()->content; ?>
</body>
</html>
