<?php
  $auth = Zend_Auth::getInstance();
  $authStorage=$auth->getIdentity();
?>
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header" style='width:30%'>

    <p class="navbar-brand" href="#">SISBIUD ICETEX<p>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div id="bs-example-navbar-collapse-1">
      <p class="navbar-text" style="text-align:right;width: 39%">Perfil: <?php echo $authStorage->perfil; ?></p>
    <p class="navbar-text" style='text-align:right;width:15%'>¡Hola <a href="#" class="navbar-link"><?php echo $authStorage->nombre_real . " " . $authStorage->apellido_real; ?>!</a></p>
    <div class='navbar-form navbar-right'>
      <a class='btn btn-primary btn-sm' href='<?php echo $this->url(array('module'=>'Index', 'controller'=>'Index','action'=>'logout')); ?>'>Cerrar Sesion</a>
    </div>
  </div><!-- /.container-fluid -->
</div>
